### PR TITLE
Support passing both URL and collection name to constructor

### PR DESCRIPTION
**Pull request by dandv**
The README gave this example,

> const keyv = new Keyv('mongodb://user:pass@localhost:27017/dbname', { collection: 'cache' });

which didn't actually set the collection name.

### CODE REVIEW

**Comment by lukechilds** [comment]
Great spot, thanks @dandv!

**Comment by lukechilds** [comment]
Sorry, @dandv had to ninja revert, how come you changed the version in package.json?

https://github.com/lukechilds/keyv-mongo/commit/ac241190f03743594ee70eecc2be4770a4153a03#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L3

**Comment by lukechilds** [comment]
Sorted in https://github.com/lukechilds/keyv-mongo/commit/633e44825d3e800c572bcc6ac04c4f108528c9f4.

Do you plane to make any more changes soon or should I publish a new release now?

**Comment by dandv** [comment]
Let's publish a new release. Hope to get the mongodb library switch soon
after the NY.

**Pull request merged**
